### ISSUE TITLE
ESLint not applying semistandard rules in `extends`

### ISSUE THREAD

**Issue by MartinDM** [standard/eslint-config-semistandard#37]
**What version of this package are you using?**
^16.0.0
eslint - V7.21.0

**What operating system, Node.js, and npm version?**
npm - 6.14.15
node- v12.22.6

**What happened?**
When adding 'semistandard' to the `.eslintrc` file in `extends`, the rules of semistandard are not applied, unless running `semistandard` directly 

**What did you expect to happen?**
ESLint to adhere to the rules in the semistandard sharable config and throw errors

**.eslintrc file:**

```
{
    "root": true,
    "extends": [
      "react-app",
      "semistandard",
      "plugin:jsx-a11y/recommended",
      "prettier"
    ],
    "plugins": [
      "jsx-a11y",
      "react",
      "jest",
      "prettier"
    ],
    "env": {
        "jest": true
      },
    "rules": {
      "comma-dangle": "off",
      "react-hooks/exhaustive-deps": "off"
    }
  }
```

Any ideas please, as was hoping to use semistandard via the `.eslintrc` file

**Comment by voxpelli** [comment]
Try adding it as the last rule set in the list of extends. Could be that one of the later rule sets overrides the relevant settings.

**Comment by MartinDM** [comment]
Thank you @voxpelli . Did seem to work and get me unstuck 👍 🎆
