### ISSUE TITLE
eslint 8.11.0 not working with this package in version 16.0.0

### ISSUE THREAD

**Issue by LittleHoopoe** [standard/eslint-config-semistandard#38]
**What version of this package are you using?** 16.0.0

**What operating system, Node.js, and npm version?** node 16.14.0 npm 8.3.1

**What happened?**
![image](https://user-images.githubusercontent.com/713681/159662579-c39941fe-7529-4e2b-83e2-8169348464d3.png)

**What did you expect to happen?** just installing it like with eslint version 7.32.0

**Are you willing to submit a pull request to fix this bug?** I'm not sure how.
This are the packages I'm want to use for my vscode linting:
"eslint": "^8.11.0",
"eslint-config-semistandard": "^16.0.0",
"eslint-plugin-promise": "^6.0.0",

this are the packages that are working great together:
"eslint": "^7.32.0",
"eslint-config-semistandard": "^16.0.0",
"eslint-plugin-promise": "^5.1.0",

let me know if you need any further information

**Comment by Divlo** [comment]
Hey! @LittleHoopoe 

Thanks for your support!
Currently, we don't support ESLint v8, but it is indeed something we want to support, see this issue for reference: https://github.com/standard/eslint-config-standard/issues/208
